import { HeroUIProvider } from "@heroui/system";
import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="en" className="dark">
			<body className="h-screen">
				<HeroUIProvider>{children}</HeroUIProvider>
			</body>
		</html>
	);
}
