import { paths } from "@/utils/paths";
import { Link } from "@heroui/link";
import { HeroUIProvider } from "@heroui/system";
import type { Metadata } from "next";
import NextLink from "next/link";
import type { PropsWithChildren } from "react";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="en" className="dark">
			<body className="h-screen">
				<HeroUIProvider>
					<nav className="flex gap-4">
						<Link as={NextLink} href={paths.login}>
							Login
						</Link>
						<Link as={NextLink} href={paths.signUp}>
							Sign Up
						</Link>
						<Link as={NextLink} href={paths.home}>
							Home
						</Link>
					</nav>
					{children}
				</HeroUIProvider>
			</body>
		</html>
	);
}
